title: Jinxin Xiao's Homepage
page-top-title: Jinxin Xiao
top-section-bg-text: Horticultural Facility and Environment
home-subtitle: Jinxin Xiao&ensp;|&ensp; 肖金鑫
copyright-text: '&copy; Jinxin Xiao 2024-2025. All Rights Reserved.'
